[target.wasm32-wasip1]
runner = "wasmtime run --dir . --"

[target.wasm32-wasip1-threads]
runner = "wasmtime run --wasi threads --wasm threads=y --dir . --"

[target.wasm32-wasip2]
runner = "wasmtime run --dir . --"

[target.wasm32-unknown-unknown]
runner = "wasmtime run --dir . --"
